board-zara-all-objs +=  board-zara-pmic.o board-zara-storage.o board-zara-gpiomux.o board-zara-display.o board-zara-gpu.o

obj-$(CONFIG_MACH_ZARA) += board-zara-camera.o board-zara.o board-zara-all.o board-zara-regulator.o board-zara-audio.o board-zara-rfkill.o htc_sleep_clk.o board-zara-keypad.o board-zara-mmc.o board-zara-wifi.o
