obj-$(CONFIG_ARCH_MSM8930) += htc_wifi_nvs.o

obj-$(CONFIG_MACH_M7_UL) += htc_4335_wl_reg.o
obj-$(CONFIG_MACH_DLXP_UL) += htc_4335_wl_reg.o

obj-$(CONFIG_ARCH_MSM8930) += ../devices-8930.o ../board-8930-gpu.o
